### ISSUE TITLE
blobtools view issue

### ISSUE THREAD

**Issue by marco91sol** [genomehubs/blobtoolkit#169]
Dear all,

I activate my btk_env environment, where I have the following version of nodejs-> 14.14.0

Then I launch the command:
blobtools view folder_with_different_json_files

I receive the following output:

Initializing viewer
Traceback (most recent call last):
File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/blobtools/lib/view.py", line 300, in static_view
driver, display = firefox_driver(args)
File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/blobtools/lib/view.py", line 212, in firefox_driver
driver = webdriver.Firefox(
File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 192, in init
self.service.start()
File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 106, in start
self.assert_process_still_running()
File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 119, in assert_process_still_running
raise WebDriverException(f"Service {self.path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/bin/blobtools", line 8, in
sys.exit(cli())
File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/blobtools/blobtools.py", line 105, in cli
sys.exit(subcommand())
File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/blobtools/lib/view.py", line 495, in cli
main(args)
File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/blobtools/lib/view.py", line 480, in main
static_view(args, loc, viewer)
File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/blobtools/lib/view.py", line 302, in static_view
format_exc(err)
File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/traceback.py", line 167, in format_exc
return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/traceback.py", line 120, in format_exception
return list(TracebackException(
File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/traceback.py", line 508, in init
self.stack = StackSummary.extract(
File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/traceback.py", line 340, in extract
if limit >= 0:
TypeError: '>=' not supported between instances of 'WebDriverException' and 'int'

How can I solve that?

Thanks for the support,
Marco

**Comment by sujaikumar** [comment]
Hi Marco
Can I check which version of BTK you are using? `blobtools -v`
And, apologies if you've already created a conda environment using some other way, but the easiest way currently (which needs to be better documented) is:

```
pip install blobtoolkit[full]
```
Or, if you prefer conda (it's easiest to reinstall the env if you already have it, so you could do `conda env remove -n btk_env` followed by:
```
conda create -y -n btk_env pip
conda activate btk_env
pip install blobtoolkit[full]
```
Do you still get the error even after creating a new env and doing a fresh pip install?

**Comment by marco91sol** [comment]
> Hi Marco Can I check which version of BTK you are using? `blobtools -v`
> 
> And, apologies if you've already installed BTK using some other way, but the easiest way currently (which needs to be better documented) is:
> 
> ```
> pip install blobtoolkit[full]
> ```
> 
> Or, if you prefer conda (it's easiest to reinstall the env if you already have it, so you could do `conda env remove -n btk_env` followed by:
> 
> ```
> conda create -y -n btk_env pip
> conda activate btk_env
> pip install blobtoolkit[full]
> ```
> 
> Do you still get the error even after creating a new env and doing a fresh pip install?

This is the version : blobtoolkit v4.1.5

I have installed it using the conda command for creating the environment and pip installation of blobtoolkit.

**Comment by sujaikumar** [comment]
Great. Thanks for confirming that :-)

1. Are you running on a remote server or on your own desktop/laptop?

2. Is the place where you installed blobtools a mac (intel or arm?) or linux/unix?

3. Can you try putting folder_with_different_json_files inside a folder called blobdirs (i.e. /path/to/blobdirs/folder_with_different_json_files) and then running this command (which allows you to host many blobdirs at once). I just want to see if the rest of the view/host stuff is working fine:
```
blobtools host /path/to/blobdirs/
```

If you get a message like
```
ERROR: Port 8000 already in use, unable to host BlobtoolKit API.
       Use: `lsof -nP -iTCP:8000 | grep LISTEN` to find the associated process.
       It may take ~30s for this port to become available when restarting BlobtoolKit API.
```
then you can retry it with something like this:
```
blobtools host --port 8030 --api-port 8031 /path/to/blobdirs/
```
And you should see a message like:
```
Starting BlobToolKit API on port 8031 (pid: 152016)
Starting BlobToolKit viewer on port 8030 (pid: 152035)
Visit http://localhost:8030 to use the interactive BlobToolKit Viewer.
```
If you're on your own desktop or laptop, just open a browser and type http://localhost:8080 in the URL bar (or http://localhost:8030) and type `all` in the search datasets box and you should see an example btk plot.

Depending on whether this is working for you or not, we'll think of other things to debug the situation! :-)

**Comment by sujaikumar** [comment]
This could be a red herring but your path suggests that you have the env inside another env?
`/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/`

**Comment by marco91sol** [comment]
> Great. Thanks for confirming that :-)
> 
> 1. Are you running on a remote server or on your own desktop/laptop?
> 2. Is the place where you installed blobtools a mac (intel or arm?) or linux/unix?
> 3. Can you try putting folder_with_different_json_files inside a folder called blobdirs (i.e. /path/to/blobdirs/folder_with_different_json_files) and then running this command (which allows you to host many blobdirs at once). I just want to see if the rest of the view/host stuff is working fine:
> 
> ```
> blobtools host /path/to/blobdirs/
> ```
> 
> If you get a message like
> 
> ```
> ERROR: Port 8000 already in use, unable to host BlobtoolKit API.
>        Use: `lsof -nP -iTCP:8000 | grep LISTEN` to find the associated process.
>        It may take ~30s for this port to become available when restarting BlobtoolKit API.
> ```
> 
> then you can retry it with something like this:
> 
> ```
> blobtools host --port 8030 --api-port 8031 /path/to/blobdirs/
> ```
> 
> And you should see a message like:
> 
> ```
> Starting BlobToolKit API on port 8031 (pid: 152016)
> Starting BlobToolKit viewer on port 8030 (pid: 152035)
> Visit http://localhost:8030 to use the interactive BlobToolKit Viewer.
> ```
> 
> If you're on your own desktop or laptop, just open a browser and type http://localhost:8080 in the URL bar (or http://localhost:8030) and type `all` in the search datasets box and you should see an example btk plot.
> 
> Depending on whether this is working for you or not, we'll think of other things to debug the situation! :-)

Unfortunately still not working. Even if I use this trick.

**Comment by sujaikumar** [comment]
Could you confirm the answer to my questions 1 and 2 please? That'll help us think of solutions...

1. Are you running on a remote server or on your own desktop/laptop?

2. Is the place where you installed blobtools a mac (intel or arm?) or linux/unix?

Also, is your btk env installed inside a snakemake env?
